name: CI.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          echo "${{github.actor}}"
          echo "${{github.event_name}}"
          echo "${{github.ref_name}}"
          echo "${{github.run_id}}"
          echo "${{job.status}}"
          echo "${{github.actor}}"
          echo "${{github.triggering_actor}}"
          echo "${{github.sha}}"
          echo "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          echo "${{github.event.head_commit.message}}"